/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controller.CategoriaController;
import dao.CategoriaDAO;
import model.Categoria;
import views.CategoriaView;
import config.ConexionBD;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import model.Producto;
import dao.ProductoDAO;
import controller.ProductoController;
import dao.ClienteDAO;
import dao.ProveedorDAO;
import controller.ClienteController;
import controller.ProveedorController;
import model.Cliente;
import model.Proveedor;

/**
 *
 * @author Cristian
 */
public class Vcategoria extends javax.swing.JFrame {

    public Vcategoria() {
        initComponents();

        nombreC.setVisible(false);
        categoriaN.setVisible(false);
        crear.setVisible(false);
        ID.setVisible(false);
        idLabel.setVisible(false);
        EliminarBoton.setVisible(false);
        actualizarLabel.setVisible(false);
        nuevoN.setVisible(false);
        ActualizarBoton.setVisible(false);
        mensaje1.setVisible(false);
        mensaje2.setVisible(false);
        mensaje3.setVisible(false);
        nuevo.setVisible(false);
        nuevolabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cliente = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nuevo = new javax.swing.JTextField();
        idLabel = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        EliminarBoton = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        mensaje2 = new javax.swing.JLabel();
        actualizarLabel = new javax.swing.JLabel();
        nuevoN = new javax.swing.JTextField();
        ActualizarBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CrearCategoria = new javax.swing.JButton();
        categoriaN = new javax.swing.JLabel();
        nombreC = new javax.swing.JTextField();
        crear = new javax.swing.JButton();
        mensaje1 = new javax.swing.JLabel();
        consultaEliminar = new javax.swing.JButton();
        Consultas = new javax.swing.JButton();
        mensaje3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        categoriaTabla = new javax.swing.JTable();
        nuevolabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productoconsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        productotable = new javax.swing.JTable();
        idproducto = new javax.swing.JLabel();
        productoid = new javax.swing.JTextField();
        producton = new javax.swing.JTextField();
        nombreproducto = new javax.swing.JLabel();
        productop = new javax.swing.JTextField();
        categoriaproducto = new javax.swing.JLabel();
        precioproducto = new javax.swing.JLabel();
        productoc = new javax.swing.JTextField();
        crearproducto = new javax.swing.JButton();
        eliminarproducto = new javax.swing.JButton();
        modificarprod = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        clienteid = new javax.swing.JTextField();
        clienten = new javax.swing.JTextField();
        cliented = new javax.swing.JTextField();
        clientet = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        clientetable = new javax.swing.JTable();
        crearc = new javax.swing.JButton();
        consultarc = new javax.swing.JButton();
        modificarc = new javax.swing.JButton();
        eliminarc = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        proveedorid = new javax.swing.JTextField();
        proveedorn = new javax.swing.JTextField();
        proveedort = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        proveedortable = new javax.swing.JTable();
        crearprov = new javax.swing.JButton();
        consultarprov = new javax.swing.JButton();
        modificarprov = new javax.swing.JButton();
        eliminarprov = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });

        idLabel.setText("Ingrese el ID de la categoria a eliminar :");

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        EliminarBoton.setText("ELIMINAR");
        EliminarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBotonActionPerformed(evt);
            }
        });

        botonActualizar.setText("ACTUALIZAR CATEGORIA");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        mensaje2.setText(".");

        actualizarLabel.setText("Ingrese el ID de la categoria a actualizar :");

        nuevoN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoNActionPerformed(evt);
            }
        });

        ActualizarBoton.setText("ACTUALIZAR");
        ActualizarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Que desea hacer?");

        CrearCategoria.setText("CREAR CATEGORIA");
        CrearCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCategoriaActionPerformed(evt);
            }
        });

        categoriaN.setText("nombre de la categoria");

        nombreC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCActionPerformed(evt);
            }
        });

        crear.setText("CREAR");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });

        mensaje1.setText(".");

        consultaEliminar.setText("ELIMINAR CATEGORIA");
        consultaEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaEliminarActionPerformed(evt);
            }
        });

        Consultas.setText("CONSULTAR CATEGORIA");
        Consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultasActionPerformed(evt);
            }
        });

        mensaje3.setText(".");

        categoriaTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre"
            }
        ));
        jScrollPane2.setViewportView(categoriaTabla);

        nuevolabel.setText("Ingrese el nuevo nombre de la categoria :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensaje3, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mensaje1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Consultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CrearCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(consultaEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(categoriaN, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(crear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addComponent(actualizarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(nuevolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nuevoN)
                            .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ActualizarBoton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Consultas)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crear)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CrearCategoria)
                        .addComponent(categoriaN)
                        .addComponent(nombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(consultaEliminar)
                    .addComponent(idLabel)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EliminarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonActualizar)
                            .addComponent(actualizarLabel)
                            .addComponent(nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nuevoN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuevolabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ActualizarBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(mensaje2)
                        .addGap(18, 18, 18)
                        .addComponent(mensaje3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mensaje1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        cliente.addTab("categorias", jPanel1);

        jLabel2.setText("¿que desea hacer?");

        productoconsultar.setText("consultar productos");
        productoconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoconsultarActionPerformed(evt);
            }
        });

        productotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nombre", "precio", "categoria"
            }
        ));
        jScrollPane1.setViewportView(productotable);
        if (productotable.getColumnModel().getColumnCount() > 0) {
            productotable.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        idproducto.setText("id");

        productoid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productoidActionPerformed(evt);
            }
        });

        nombreproducto.setText("nombre");

        categoriaproducto.setText("categoria");

        precioproducto.setText("precio");

        crearproducto.setText("crear");
        crearproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearproductoActionPerformed(evt);
            }
        });

        eliminarproducto.setText("eliminar");
        eliminarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarproductoActionPerformed(evt);
            }
        });

        modificarprod.setText("modificar");
        modificarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarprodActionPerformed(evt);
            }
        });

        jLabel4.setText("para ingresar un producto no se ingresa el id");

        jLabel5.setText("para eliminar solo hace falta ingresar el id");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(184, 269, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addComponent(crearproducto))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(categoriaproducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idproducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nombreproducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(precioproducto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(productoconsultar)
                        .addGap(5, 5, 5)
                        .addComponent(eliminarproducto)
                        .addGap(18, 18, 18)
                        .addComponent(modificarprod))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(productop)
                            .addComponent(producton)
                            .addComponent(productoid)
                            .addComponent(productoc, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(210, 210, 210))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addGap(88, 88, 88)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idproducto)
                    .addComponent(productoid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(producton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreproducto)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precioproducto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriaproducto)
                    .addComponent(productoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearproducto)
                    .addComponent(eliminarproducto)
                    .addComponent(modificarprod)
                    .addComponent(productoconsultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cliente.addTab("productos", jPanel2);

        jLabel6.setText("¿Que desea hacer ?");

        jLabel7.setText("id");

        jLabel8.setText("nombre");

        jLabel9.setText("direccion");

        jLabel10.setText("telefono");

        clientetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nombre", "direccion", "telefono"
            }
        ));
        jScrollPane3.setViewportView(clientetable);
        if (clientetable.getColumnModel().getColumnCount() > 0) {
            clientetable.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        crearc.setText("crear");
        crearc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearcActionPerformed(evt);
            }
        });

        consultarc.setText("consultar");
        consultarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarcActionPerformed(evt);
            }
        });

        modificarc.setText("modificar");
        modificarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarcActionPerformed(evt);
            }
        });

        eliminarc.setText("eliminar");
        eliminarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcActionPerformed(evt);
            }
        });

        jLabel17.setText("Para el ingreso de un cliente no se debe ingresar el id");

        jLabel18.setText("para la eliminacion solo es necesario el id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57)
                                        .addComponent(clienteid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(clienten, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cliented, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(clientet, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(crearc)
                                .addGap(19, 19, 19)
                                .addComponent(consultarc)
                                .addGap(18, 18, 18)
                                .addComponent(modificarc)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarc))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(clienteid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(clienten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cliented, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(clientet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearc)
                    .addComponent(consultarc)
                    .addComponent(modificarc)
                    .addComponent(eliminarc))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cliente.addTab("cliente", jPanel3);

        jLabel11.setText("¿Que desea hacer?");

        jLabel12.setText("id");

        jLabel13.setText("nombre");

        jLabel14.setText("telefono");

        proveedortable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nombre", "telefono"
            }
        ));
        jScrollPane4.setViewportView(proveedortable);
        if (proveedortable.getColumnModel().getColumnCount() > 0) {
            proveedortable.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        crearprov.setText("crear");
        crearprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearprovActionPerformed(evt);
            }
        });

        consultarprov.setText("consultar");
        consultarprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarprovActionPerformed(evt);
            }
        });

        modificarprov.setText("modificar");
        modificarprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarprovActionPerformed(evt);
            }
        });

        eliminarprov.setText("eliminar");
        eliminarprov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarprovActionPerformed(evt);
            }
        });

        jLabel15.setText("para ingresar un proveedor no se requiere id");

        jLabel16.setText("para eliminar solo es necesario el id");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(crearprov)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(proveedorid, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(proveedorn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(proveedort, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(consultarprov)
                                .addGap(18, 18, 18)
                                .addComponent(modificarprov)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarprov)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(proveedorid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(proveedorn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(proveedort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearprov)
                    .addComponent(consultarprov)
                    .addComponent(modificarprov)
                    .addComponent(eliminarprov))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cliente.addTab("proveedor", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cliente)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cliente)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        CategoriaController categoriaboton = new CategoriaController();
        categoriaboton.crearCategoriaboton(nombreC.getText());
        mensaje1.setText("categoria creada exitosamente");
        mensaje1.setVisible(true);
        mensaje3.setVisible(false);
        mensaje2.setVisible(false);

    }//GEN-LAST:event_crearActionPerformed

    private void CrearCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCategoriaActionPerformed
        nombreC.setVisible(true);
        categoriaN.setVisible(true);
        crear.setVisible(true);
        ID.setVisible(false);
        idLabel.setVisible(false);
        EliminarBoton.setVisible(false);
        actualizarLabel.setVisible(false);
        nuevoN.setVisible(false);
        ActualizarBoton.setVisible(false);
        nuevo.setVisible(false);
        nuevolabel.setVisible(false);

    }//GEN-LAST:event_CrearCategoriaActionPerformed

    private void ConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultasActionPerformed
        DefaultTableModel model = (DefaultTableModel) categoriaTabla.getModel();
        model.setRowCount(0);

        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leer = categoria.leerCategorias();
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for (Categoria c : categorias) {
            columnas[0] = c.getId();
            columnas[1] = c.getNombre();
            model.addRow(columnas);

        }
        nombreC.setVisible(false);
        categoriaN.setVisible(false);
        crear.setVisible(false);
        actualizarLabel.setVisible(false);
        nuevoN.setVisible(false);
        ActualizarBoton.setVisible(false);
        nuevo.setVisible(false);
        nuevolabel.setVisible(false);
        mensaje1.setVisible(false);
        mensaje2.setVisible(false);
        mensaje3.setVisible(false);
    }//GEN-LAST:event_ConsultasActionPerformed

    private void consultaEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaEliminarActionPerformed
        // TODO add your handling code here:

        leervista();
        ID.setVisible(true);
        idLabel.setVisible(true);
        EliminarBoton.setVisible(true);
        nombreC.setVisible(false);
        categoriaN.setVisible(false);
        crear.setVisible(false);
        actualizarLabel.setVisible(false);
        nuevoN.setVisible(false);
        ActualizarBoton.setVisible(false);
        nuevo.setVisible(false);
        nuevolabel.setVisible(false);
    }//GEN-LAST:event_consultaEliminarActionPerformed

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed

    }//GEN-LAST:event_IDActionPerformed

    private void EliminarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBotonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) categoriaTabla.getModel();
        model.setRowCount(0);

        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leer = categoria.leerCategorias();
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for (Categoria c : categorias) {
            columnas[0] = c.getId();
            columnas[1] = c.getNombre();
            model.addRow(columnas);

        }
        CategoriaController categoriae = new CategoriaController();
        categoriae.eliminarCategoriav(Integer.parseInt(ID.getText()));
        mensaje2.setText("categoria eliminada exitosamente");
        mensaje2.setVisible(true);
        mensaje1.setVisible(false);
        mensaje3.setVisible(false);
    }//GEN-LAST:event_EliminarBotonActionPerformed

    private void nuevoNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoNActionPerformed

    private void ActualizarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarBotonActionPerformed
        mensaje3.setVisible(true);
        mensaje3.setText("categoria actualizada exitosamente");
        CategoriaController categoriaA = new CategoriaController();
        categoriaA.actualizarCategoriav(Integer.parseInt(nuevo.getText()), nuevoN.getText());
        mensaje1.setVisible(false);
        mensaje2.setVisible(false);
    }//GEN-LAST:event_ActualizarBotonActionPerformed

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nuevoActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        leervista();
        actualizarLabel.setVisible(true);
        nuevoN.setVisible(true);
        ActualizarBoton.setVisible(true);
        nuevo.setVisible(true);
        nuevolabel.setVisible(true);
        nombreC.setVisible(false);
        categoriaN.setVisible(false);
        crear.setVisible(false);
        ID.setVisible(false);
        idLabel.setVisible(false);
        EliminarBoton.setVisible(false);
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void crearproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearproductoActionPerformed
        ProductoController crearprod = new ProductoController();
        crearprod.crearproductov(producton.getText(), Integer.parseInt(productop.getText()), Integer.parseInt(productoc.getText()));
    }//GEN-LAST:event_crearproductoActionPerformed

    private void productoidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productoidActionPerformed

    private void productoconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productoconsultarActionPerformed
        productoleerv();
    }//GEN-LAST:event_productoconsultarActionPerformed

    private void modificarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarprodActionPerformed

        ProductoController modififcarp = new ProductoController();
        modififcarp.acualizarProductov(Integer.parseInt(productoid.getText()), producton.getText(), Integer.parseInt(productop.getText()), Integer.parseInt(productoc.getText()));
    }//GEN-LAST:event_modificarprodActionPerformed

    private void eliminarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarproductoActionPerformed
        ProductoController eliminarp = new ProductoController();
        eliminarp.eliminarProducto(Integer.parseInt(productoid.getText()));
    }//GEN-LAST:event_eliminarproductoActionPerformed

    private void crearcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearcActionPerformed
        ClienteController crearc = new ClienteController();
        crearc.crearcliente(0, clienten.getText(), cliented.getText(), clientet.getText());

    }//GEN-LAST:event_crearcActionPerformed

    private void consultarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarcActionPerformed
        clienteleerv();
    }//GEN-LAST:event_consultarcActionPerformed

    private void modificarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarcActionPerformed
        ClienteController modificarc = new ClienteController();
        modificarc.actualizarcliente(Integer.parseInt(clienteid.getText()), clienten.getText(), cliented.getText(), clientet.getText());
    }//GEN-LAST:event_modificarcActionPerformed

    private void eliminarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcActionPerformed
        ClienteController eliminarc = new ClienteController();
        eliminarc.eliminarcliente(Integer.parseInt(clienteid.getText()));
    }//GEN-LAST:event_eliminarcActionPerformed

    private void crearprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearprovActionPerformed
        ProveedorController crearprov = new ProveedorController();
        crearprov.crearproveedor(0, proveedorn.getText(), proveedort.getText());
    }//GEN-LAST:event_crearprovActionPerformed

    private void consultarprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarprovActionPerformed
        proveedorleerv();
    }//GEN-LAST:event_consultarprovActionPerformed

    private void modificarprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarprovActionPerformed
        ProveedorController modificarprov = new ProveedorController();
        modificarprov.actualizarproveedor(Integer.parseInt(proveedorid.getText()), proveedorn.getText(), proveedort.getText());
    }//GEN-LAST:event_modificarprovActionPerformed

    private void eliminarprovActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarprovActionPerformed
        ProveedorController eliminarprov = new ProveedorController();
        eliminarprov.eliminarproveedor(Integer.parseInt(proveedorid.getText()));
    }//GEN-LAST:event_eliminarprovActionPerformed

    public void leervista() {
        DefaultTableModel model = (DefaultTableModel) categoriaTabla.getModel();
        model.setRowCount(0);

        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leer = categoria.leerCategorias();
        categorias.addAll(leer);

        Object columnas[] = new Object[2];
        for (Categoria c : categorias) {
            columnas[0] = c.getId();
            columnas[1] = c.getNombre();
            model.addRow(columnas);
        }
    }

    public void productoleerv() {
        DefaultTableModel model = (DefaultTableModel) productotable.getModel();
        model.setRowCount(0);

        ArrayList<Producto> productos = new ArrayList();
        ProductoController producto = new ProductoController();
        List<Producto> leerp = producto.leerProductos();
        productos.addAll(leerp);

        Object columnas[] = new Object[4];
        for (Producto p : productos) {
            columnas[0] = p.getId();
            columnas[1] = p.getNombre();
            columnas[2] = p.getPrecio();
            columnas[3] = p.getCategoria();
            model.addRow(columnas);
        }
    }

    public void clienteleerv() {
        DefaultTableModel model = (DefaultTableModel) clientetable.getModel();
        model.setRowCount(0);

        ArrayList<Cliente> clientes = new ArrayList();
        ClienteController cliente = new ClienteController();
        List<Cliente> leerc = cliente.leerClientes();
        clientes.addAll(leerc);

        Object columnas[] = new Object[4];
        for (Cliente c : clientes) {
            columnas[0] = c.getId();
            columnas[1] = c.getNombre();
            columnas[2] = c.getDireccion();
            columnas[3] = c.getTelefono();
            model.addRow(columnas);
        }
    }

    public void proveedorleerv() {
        DefaultTableModel model = (DefaultTableModel) proveedortable.getModel();
        model.setRowCount(0);

        ArrayList<Proveedor> proveedores = new ArrayList();
        ProveedorController proveedor = new ProveedorController();
        List<Proveedor> leerprov = proveedor.leerProveedor();
        proveedores.addAll(leerprov);

        Object columnas[] = new Object[3];
        for (Proveedor prov : proveedores) {
            columnas[0] = prov.getId();
            columnas[1] = prov.getNombre();
            columnas[2] = prov.getTelefono();
            model.addRow(columnas);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActualizarBoton;
    private javax.swing.JButton Consultas;
    private javax.swing.JButton CrearCategoria;
    private javax.swing.JButton EliminarBoton;
    private javax.swing.JTextField ID;
    private javax.swing.JLabel actualizarLabel;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JLabel categoriaN;
    private javax.swing.JTable categoriaTabla;
    private javax.swing.JLabel categoriaproducto;
    private javax.swing.JTabbedPane cliente;
    private javax.swing.JTextField cliented;
    private javax.swing.JTextField clienteid;
    private javax.swing.JTextField clienten;
    private javax.swing.JTextField clientet;
    private javax.swing.JTable clientetable;
    private javax.swing.JButton consultaEliminar;
    private javax.swing.JButton consultarc;
    private javax.swing.JButton consultarprov;
    private javax.swing.JButton crear;
    private javax.swing.JButton crearc;
    private javax.swing.JButton crearproducto;
    private javax.swing.JButton crearprov;
    private javax.swing.JButton eliminarc;
    private javax.swing.JButton eliminarproducto;
    private javax.swing.JButton eliminarprov;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel idproducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JLabel mensaje3;
    private javax.swing.JButton modificarc;
    private javax.swing.JButton modificarprod;
    private javax.swing.JButton modificarprov;
    private javax.swing.JTextField nombreC;
    private javax.swing.JLabel nombreproducto;
    private javax.swing.JTextField nuevo;
    private javax.swing.JTextField nuevoN;
    private javax.swing.JLabel nuevolabel;
    private javax.swing.JLabel precioproducto;
    private javax.swing.JTextField productoc;
    private javax.swing.JButton productoconsultar;
    private javax.swing.JTextField productoid;
    private javax.swing.JTextField producton;
    private javax.swing.JTextField productop;
    private javax.swing.JTable productotable;
    private javax.swing.JTextField proveedorid;
    private javax.swing.JTextField proveedorn;
    private javax.swing.JTextField proveedort;
    private javax.swing.JTable proveedortable;
    // End of variables declaration//GEN-END:variables

}
