/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import config.DatabaseConnection;
import dao.LibroDAO;
import dao.UsuarioDAO;
import dao.PrestamoDAO;
import dao.CategoriaDAO;
import model.Categoria;
import model.Libro;
import model.Usuario;
import model.Prestamo;
import controller.CategoriaController;
import controller.LibroController;
import controller.UsuarioController;
import Controller.PrestamoController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class Vistabiblioteca extends javax.swing.JPanel {

    /**
     * Creates new form Vistabiblioteca
     */
    public Vistabiblioteca() {
        initComponents();
        nombrel.setVisible(false);
        autorl.setVisible(false);
        anol.setVisible(false);
        editoriall.setVisible(false);
        isbnl.setVisible(false);
        idl.setVisible(false);
        butoncrear.setVisible(false);
        botonactualizar.setVisible(false);
        botoneliminar.setVisible(false);
        ltitulo.setVisible(false);
        lautor.setVisible(false);
        leditorial.setVisible(false);
        lano.setVisible(false);
        lisbn.setVisible(false);
        lid.setVisible(false);

        crearusuario.setVisible(false);
        actualizarusuario.setVisible(false);
        eliminarusuario.setVisible(false);
        idu.setVisible(false);
        nombreu.setVisible(false);
        emailu.setVisible(false);
        telefonou.setVisible(false);
        usuarioid.setVisible(false);
        usuarion.setVisible(false);
        usuarioe.setVisible(false);
        usuariot.setVisible(false);

        cid.setVisible(false);
        idc.setVisible(false);
        nombrec.setVisible(false);
        cnombre.setVisible(false);
        cactualizar.setVisible(false);
        celiminar.setVisible(false);
        ccrear.setVisible(false);

        plibro.setVisible(false);
        librop.setVisible(false);
        usuariop.setVisible(false);
        pusuario.setVisible(false);
        fechap.setVisible(false);
        pfecha.setVisible(false);
        dfecha.setVisible(false);
        fechad.setVisible(false);
        idp.setVisible(false);
        idpnuevo.setVisible(false);
        crearp.setVisible(false);
        pactualizar.setVisible(false);
        peliminar.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        crearl = new javax.swing.JButton();
        ltitulo = new javax.swing.JLabel();
        nombrel = new javax.swing.JTextField();
        lautor = new javax.swing.JLabel();
        autorl = new javax.swing.JTextField();
        leditorial = new javax.swing.JLabel();
        editoriall = new javax.swing.JTextField();
        lano = new javax.swing.JLabel();
        anol = new javax.swing.JTextField();
        lisbn = new javax.swing.JLabel();
        isbnl = new javax.swing.JTextField();
        butoncrear = new javax.swing.JButton();
        mostrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        librotable = new javax.swing.JTable();
        lid = new javax.swing.JLabel();
        idl = new javax.swing.JTextField();
        actualizar = new javax.swing.JButton();
        botonactualizar = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        botoneliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        idu = new javax.swing.JLabel();
        registrar = new javax.swing.JButton();
        consultaru = new javax.swing.JButton();
        actualizaru = new javax.swing.JButton();
        elinminaru = new javax.swing.JButton();
        nombreu = new javax.swing.JLabel();
        emailu = new javax.swing.JLabel();
        telefonou = new javax.swing.JLabel();
        usuarion = new javax.swing.JTextField();
        usuarioe = new javax.swing.JTextField();
        usuariot = new javax.swing.JTextField();
        crearusuario = new javax.swing.JButton();
        actualizarusuario = new javax.swing.JButton();
        eliminarusuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuariotable = new javax.swing.JTable();
        usuarioid = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        crearprestamo = new javax.swing.JButton();
        librop = new javax.swing.JLabel();
        plibro = new javax.swing.JTextField();
        usuariop = new javax.swing.JLabel();
        pusuario = new javax.swing.JTextField();
        fechap = new javax.swing.JLabel();
        fechad = new javax.swing.JLabel();
        pfecha = new javax.swing.JTextField();
        dfecha = new javax.swing.JTextField();
        crearp = new javax.swing.JButton();
        consultarp = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        prestamotable = new javax.swing.JTable();
        pactualizar = new javax.swing.JButton();
        idp = new javax.swing.JLabel();
        idpnuevo = new javax.swing.JTextField();
        peliminar = new javax.swing.JButton();
        actualizarp = new javax.swing.JButton();
        eliminarp = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cnombre = new javax.swing.JLabel();
        crearc = new javax.swing.JButton();
        nombrec = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        categoriatable = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        ccrear = new javax.swing.JButton();
        mostarc = new javax.swing.JButton();
        cid = new javax.swing.JLabel();
        idc = new javax.swing.JTextField();
        actualizarc = new javax.swing.JButton();
        eliminarc = new javax.swing.JButton();
        cactualizar = new javax.swing.JButton();
        celiminar = new javax.swing.JButton();

        crearl.setText("Crear");
        crearl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearlActionPerformed(evt);
            }
        });

        ltitulo.setText("titulo");

        lautor.setText("autor");

        leditorial.setText("editorial");

        lano.setText("año publicacion");

        lisbn.setText("isbn");

        butoncrear.setText("crearlibro");
        butoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butoncrearActionPerformed(evt);
            }
        });

        mostrar.setText("mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });

        librotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "TITULO", "AUTOR", "EDITORIAL", "AÑO P", "ISBN"
            }
        ));
        jScrollPane1.setViewportView(librotable);
        if (librotable.getColumnModel().getColumnCount() > 0) {
            librotable.getColumnModel().getColumn(0).setMaxWidth(100);
            librotable.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        lid.setText("id");

        actualizar.setText("actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        botonactualizar.setText("Actualizarlibro");
        botonactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonactualizarActionPerformed(evt);
            }
        });

        eliminar.setText("eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        botoneliminar.setText("EliminarLibro");
        botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("que desea hacer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1023, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lid, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ltitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lautor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lano)
                        .addComponent(leditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrel, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idl, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autorl, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editoriall, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(anol, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(isbnl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(butoncrear)
                        .addGap(34, 34, 34)
                        .addComponent(botonactualizar)
                        .addGap(32, 32, 32)
                        .addComponent(botoneliminar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(crearl)
                            .addGap(18, 18, 18)
                            .addComponent(mostrar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(actualizar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminar))))
                .addGap(534, 534, 534))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearl)
                    .addComponent(mostrar)
                    .addComponent(actualizar)
                    .addComponent(eliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lid)
                    .addComponent(idl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ltitulo)
                    .addComponent(nombrel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lautor)
                    .addComponent(autorl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leditorial)
                    .addComponent(editoriall, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lano)
                    .addComponent(anol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lisbn)
                    .addComponent(isbnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botoneliminar)
                    .addComponent(botonactualizar)
                    .addComponent(butoncrear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("libro", jPanel1);

        idu.setText("id usuario");

        registrar.setText("registrar");
        registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarActionPerformed(evt);
            }
        });

        consultaru.setText("consultar");
        consultaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaruActionPerformed(evt);
            }
        });

        actualizaru.setText("actualizar");
        actualizaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizaruActionPerformed(evt);
            }
        });

        elinminaru.setText("eliminar");
        elinminaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elinminaruActionPerformed(evt);
            }
        });

        nombreu.setText("nombre");

        emailu.setText("email");

        telefonou.setText("telefono");

        crearusuario.setText("crear");
        crearusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearusuarioActionPerformed(evt);
            }
        });

        actualizarusuario.setText("actualizar");
        actualizarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarusuarioActionPerformed(evt);
            }
        });

        eliminarusuario.setText("eliminar");
        eliminarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarusuarioActionPerformed(evt);
            }
        });

        usuariotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "nombre", "email", "telefono"
            }
        ));
        jScrollPane2.setViewportView(usuariotable);
        if (usuariotable.getColumnModel().getColumnCount() > 0) {
            usuariotable.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jLabel7.setText("que desea hacer");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(crearusuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(actualizarusuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eliminarusuario))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(registrar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(consultaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(actualizaru)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(elinminaru))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idu)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(emailu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nombreu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(telefonou))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(usuarion, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(usuarioe, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(usuariot, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(usuarioid, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addGap(3, 3, 3))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(registrar)
                            .addComponent(consultaru)
                            .addComponent(actualizaru)
                            .addComponent(elinminaru))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idu)
                            .addComponent(usuarioid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreu)
                            .addComponent(usuarion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailu)
                            .addComponent(usuarioe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(telefonou)
                            .addComponent(usuariot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearusuario)
                            .addComponent(actualizarusuario)
                            .addComponent(eliminarusuario))))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("usuario", jPanel2);

        jLabel9.setText("que desea hacer");

        crearprestamo.setText("crear");
        crearprestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearprestamoActionPerformed(evt);
            }
        });

        librop.setText("id _libro");

        usuariop.setText("id_usuario");

        fechap.setText("fecha prestamo");

        fechad.setText("fecha devolucion");

        crearp.setText("crear");
        crearp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearpActionPerformed(evt);
            }
        });

        consultarp.setText("mostar");
        consultarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarpActionPerformed(evt);
            }
        });

        prestamotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "id_libro", "id_usuario", "fecha prestamo", "fecha devolucion"
            }
        ));
        jScrollPane3.setViewportView(prestamotable);
        if (prestamotable.getColumnModel().getColumnCount() > 0) {
            prestamotable.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        pactualizar.setText("actualizar");
        pactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pactualizarActionPerformed(evt);
            }
        });

        idp.setText("id  prestasmo");

        peliminar.setText("eliminar");
        peliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliminarActionPerformed(evt);
            }
        });

        actualizarp.setText("actualizar");
        actualizarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarpActionPerformed(evt);
            }
        });

        eliminarp.setText("eliminar");
        eliminarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crearp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(peliminar))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(crearprestamo)
                        .addGap(18, 18, 18)
                        .addComponent(consultarp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(actualizarp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eliminarp))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(librop, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usuariop))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(plibro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechap, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(dfecha, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(idpnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearprestamo)
                            .addComponent(consultarp)
                            .addComponent(actualizarp)
                            .addComponent(eliminarp))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(librop)
                            .addComponent(plibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(usuariop)
                            .addComponent(pusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechap)
                            .addComponent(pfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechad)
                            .addComponent(dfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idp)
                            .addComponent(idpnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearp)
                            .addComponent(pactualizar)
                            .addComponent(peliminar))))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("prestamo", jPanel3);

        jLabel11.setText("que desea hacer");

        cnombre.setText("nombre");

        crearc.setText("crear");
        crearc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearcActionPerformed(evt);
            }
        });

        categoriatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "nombre"
            }
        ));
        jScrollPane4.setViewportView(categoriatable);
        if (categoriatable.getColumnModel().getColumnCount() > 0) {
            categoriatable.getColumnModel().getColumn(0).setMaxWidth(90);
        }

        ccrear.setText("crear");
        ccrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccrearActionPerformed(evt);
            }
        });

        mostarc.setText("mostrar");
        mostarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostarcActionPerformed(evt);
            }
        });

        cid.setText("Id");

        actualizarc.setText("actualizar");
        actualizarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarcActionPerformed(evt);
            }
        });

        eliminarc.setText("eliminar");
        eliminarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarcActionPerformed(evt);
            }
        });

        cactualizar.setText("actualizar");
        cactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cactualizarActionPerformed(evt);
            }
        });

        celiminar.setText("eliminar");
        celiminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                celiminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(74, 74, 74))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(crearc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mostarc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(actualizarc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(eliminarc))
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(ccrear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cactualizar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(celiminar))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nombrec, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                    .addComponent(idc, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 267, Short.MAX_VALUE)))
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(crearc)
                            .addComponent(mostarc)
                            .addComponent(actualizarc)
                            .addComponent(eliminarc))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cid)
                            .addComponent(idc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnombre)
                            .addComponent(nombrec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addComponent(jLabel13)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ccrear)
                            .addComponent(cactualizar)
                            .addComponent(celiminar))))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("categoria", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void butoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butoncrearActionPerformed
        LibroController crearl = new LibroController();
        crearl.crearLibro(nombrel.getText(), autorl.getText(), editoriall.getText(), Integer.parseInt(anol.getText()), isbnl.getText());

    }//GEN-LAST:event_butoncrearActionPerformed

    private void crearlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearlActionPerformed

        nombrel.setVisible(true);
        autorl.setVisible(true);
        anol.setVisible(true);
        editoriall.setVisible(true);
        isbnl.setVisible(true);
        butoncrear.setVisible(true);
        ltitulo.setVisible(true);
        lautor.setVisible(true);
        leditorial.setVisible(true);
        lano.setVisible(true);
        lisbn.setVisible(true);
        lid.setVisible(false);
        botonactualizar.setVisible(false);
        botoneliminar.setVisible(false);
    }//GEN-LAST:event_crearlActionPerformed

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        DefaultTableModel model = (DefaultTableModel) librotable.getModel();
        model.setRowCount(0);

        ArrayList<Libro> libros = new ArrayList();
        LibroController libro = new LibroController();
        List<Libro> leer = libro.leerLibros();
        libros.addAll(leer);

        Object columnas[] = new Object[6];
        for (Libro l : libros) {
            columnas[0] = l.getId_libro();
            columnas[1] = l.getTitulo();
            columnas[2] = l.getAutor();
            columnas[3] = l.getEditorial();
            columnas[4] = l.getAnio_publicacion();
            columnas[5] = l.getIsbn();
            model.addRow(columnas);

        }

        nombrel.setVisible(false);
        autorl.setVisible(false);
        anol.setVisible(false);
        editoriall.setVisible(false);
        isbnl.setVisible(false);
        butoncrear.setVisible(false);
        botonactualizar.setVisible(false);
        idl.setVisible(false);
        ltitulo.setVisible(false);
        lautor.setVisible(false);
        leditorial.setVisible(false);
        lano.setVisible(false);
        lisbn.setVisible(false);
        lid.setVisible(false);

    }//GEN-LAST:event_mostrarActionPerformed

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        nombrel.setVisible(true);
        autorl.setVisible(true);
        anol.setVisible(true);
        editoriall.setVisible(true);
        isbnl.setVisible(true);
        ltitulo.setVisible(true);
        lautor.setVisible(true);
        leditorial.setVisible(true);
        lano.setVisible(true);
        lisbn.setVisible(true);
        lid.setVisible(true);
        idl.setVisible(true);
        botonactualizar.setVisible(true);
        butoncrear.setVisible(false);
        botoneliminar.setVisible(false);
    }//GEN-LAST:event_actualizarActionPerformed

    private void botonactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonactualizarActionPerformed

        LibroController actualizarl = new LibroController();

        actualizarl.actualizarLibros(Integer.parseInt(idl.getText()), nombrel.getText(), autorl.getText(), editoriall.getText(), Integer.parseInt(anol.getText()), isbnl.getText());
    }//GEN-LAST:event_botonactualizarActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        nombrel.setVisible(false);
        autorl.setVisible(false);
        anol.setVisible(false);
        editoriall.setVisible(false);
        idl.setVisible(true);
        isbnl.setVisible(false);
        ltitulo.setVisible(false);
        lautor.setVisible(false);
        leditorial.setVisible(false);
        lano.setVisible(false);
        lisbn.setVisible(false);
        lid.setVisible(true);
        botonactualizar.setVisible(false);
        butoncrear.setVisible(false);
        botoneliminar.setVisible(true);

    }//GEN-LAST:event_eliminarActionPerformed

    private void botoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarActionPerformed
        LibroController eliminarl = new LibroController();
        eliminarl.eliminarLibros(Integer.parseInt(idl.getText()));
    }//GEN-LAST:event_botoneliminarActionPerformed

    private void registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarActionPerformed
        idu.setVisible(false);
        nombreu.setVisible(true);
        emailu.setVisible(true);
        telefonou.setVisible(false);
        usuarioid.setVisible(false);
        usuarion.setVisible(true);
        usuarioe.setVisible(true);
        usuariot.setVisible(true);
        crearusuario.setVisible(true);
        actualizarusuario.setVisible(false);
        eliminarusuario.setVisible(false);
        telefonou.setVisible(true);

    }//GEN-LAST:event_registrarActionPerformed

    private void crearusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearusuarioActionPerformed
        UsuarioController crearu = new UsuarioController();
        crearu.crearUsuario(usuarion.getText(), usuarioe.getText(), usuariot.getText());
    }//GEN-LAST:event_crearusuarioActionPerformed

    private void consultaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaruActionPerformed
        crearusuario.setVisible(false);
        actualizarusuario.setVisible(false);
        eliminarusuario.setVisible(false);
        idu.setVisible(false);
        nombreu.setVisible(false);
        emailu.setVisible(false);
        telefonou.setVisible(false);
        usuarioid.setVisible(false);
        usuarion.setVisible(false);
        usuarioe.setVisible(false);
        usuariot.setVisible(false);

        mostrarusuarios();
    }//GEN-LAST:event_consultaruActionPerformed

    private void actualizaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizaruActionPerformed
        idu.setVisible(true);
        nombreu.setVisible(true);
        emailu.setVisible(true);
        telefonou.setVisible(false);
        usuarioid.setVisible(true);
        usuarion.setVisible(true);
        usuarioe.setVisible(true);
        usuariot.setVisible(true);
        crearusuario.setVisible(false);
        actualizarusuario.setVisible(true);
        eliminarusuario.setVisible(false);
        telefonou.setVisible(true);
        mostrarusuarios();
    }//GEN-LAST:event_actualizaruActionPerformed

    private void actualizarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarusuarioActionPerformed

        UsuarioController actualizaru = new UsuarioController();
        actualizaru.actualizarUsuario(Integer.parseInt(usuarioid.getText()), usuarion.getText(), usuarioe.getText(), usuariot.getText());
    }//GEN-LAST:event_actualizarusuarioActionPerformed

    private void elinminaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elinminaruActionPerformed
        // TODO add your handling cod        idu.setVisible(true);
        nombreu.setVisible(false);
        emailu.setVisible(false);
        telefonou.setVisible(false);
        usuarioid.setVisible(true);
        usuarion.setVisible(false);
        usuarioe.setVisible(false);
        usuariot.setVisible(false);
        crearusuario.setVisible(false);
        actualizarusuario.setVisible(false);
        eliminarusuario.setVisible(true);
        telefonou.setVisible(false);
        idu.setVisible(true);
        mostrarusuarios();
    }//GEN-LAST:event_elinminaruActionPerformed

    private void eliminarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarusuarioActionPerformed

        UsuarioController eliminaru = new UsuarioController();
        eliminaru.eliminarUsuarios(Integer.parseInt(usuarioid.getText()));
    }//GEN-LAST:event_eliminarusuarioActionPerformed

    private void crearprestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearprestamoActionPerformed
        plibro.setVisible(true);
        librop.setVisible(true);
        usuariop.setVisible(true);
        pusuario.setVisible(true);
        fechap.setVisible(true);
        pfecha.setVisible(true);
        dfecha.setVisible(true);
        fechad.setVisible(true);
        idp.setVisible(false);
        idpnuevo.setVisible(false);
        crearp.setVisible(true);
        pactualizar.setVisible(false);
        peliminar.setVisible(false);

    }//GEN-LAST:event_crearprestamoActionPerformed

    private void crearpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearpActionPerformed
        PrestamoController crearp = new PrestamoController();
        crearp.crearPrestamo(Integer.parseInt(plibro.getText()), Integer.parseInt(pusuario.getText()), pfecha.getText(), dfecha.getText());
    }//GEN-LAST:event_crearpActionPerformed

    private void consultarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarpActionPerformed
        mostrarprestamos();
        plibro.setVisible(false);
        librop.setVisible(false);
        usuariop.setVisible(false);
        pusuario.setVisible(false);
        fechap.setVisible(false);
        pfecha.setVisible(false);
        dfecha.setVisible(false);
        fechad.setVisible(false);
        idp.setVisible(false);
        idpnuevo.setVisible(false);
        crearp.setVisible(false);
        pactualizar.setVisible(false);
        peliminar.setVisible(false);

    }//GEN-LAST:event_consultarpActionPerformed

    private void pactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pactualizarActionPerformed
        PrestamoController actualizarp = new PrestamoController();
        actualizarp.actualizarPrestamo(Integer.parseInt(idpnuevo.getText()), Integer.parseInt(plibro.getText()), Integer.parseInt(pusuario.getText()), pfecha.getText(), dfecha.getText());
    }//GEN-LAST:event_pactualizarActionPerformed

    private void peliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliminarActionPerformed
        PrestamoController eliminarp = new PrestamoController();
        eliminarp.eliminarPrestamo(Integer.parseInt(idpnuevo.getText()));
    }//GEN-LAST:event_peliminarActionPerformed

    private void ccrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccrearActionPerformed
        CategoriaController crearc = new CategoriaController();
        crearc.crearCategoria(nombrec.getText());
    }//GEN-LAST:event_ccrearActionPerformed

    private void mostarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostarcActionPerformed
        mostrarcategorias();
    }//GEN-LAST:event_mostarcActionPerformed

    private void cactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cactualizarActionPerformed

        CategoriaController actualizarc = new CategoriaController();
        actualizarc.actualizarCategoria(Integer.parseInt(idc.getText()), nombrec.getText());
    }//GEN-LAST:event_cactualizarActionPerformed

    private void celiminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_celiminarActionPerformed

        CategoriaController eliminarc = new CategoriaController();
        eliminarc.eliminarCategoriaVista(Integer.parseInt(idc.getText()));
    }//GEN-LAST:event_celiminarActionPerformed

    private void actualizarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarcActionPerformed
        mostrarcategorias();
        idc.setVisible(true);
        cid.setVisible(true);
        nombrec.setVisible(true);
        cnombre.setVisible(true);
        ccrear.setVisible(false);
        cactualizar.setVisible(true);
        celiminar.setVisible(false);
    }//GEN-LAST:event_actualizarcActionPerformed

    private void eliminarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarcActionPerformed
        mostrarcategorias();
        idc.setVisible(true);
        cid.setVisible(true);
        nombrec.setVisible(false);
        cnombre.setVisible(false);
        ccrear.setVisible(false);
        cactualizar.setVisible(false);
        celiminar.setVisible(true);
    }//GEN-LAST:event_eliminarcActionPerformed

    private void crearcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearcActionPerformed
        idc.setVisible(false);
        cid.setVisible(false);
        nombrec.setVisible(true);
        cnombre.setVisible(true);
        ccrear.setVisible(true);
        cactualizar.setVisible(false);
        celiminar.setVisible(false);
    }//GEN-LAST:event_crearcActionPerformed

    private void actualizarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarpActionPerformed
        plibro.setVisible(true);
        librop.setVisible(true);
        usuariop.setVisible(true);
        pusuario.setVisible(true);
        fechap.setVisible(true);
        pfecha.setVisible(true);
        dfecha.setVisible(true);
        fechad.setVisible(true);
        idp.setVisible(true);
        idpnuevo.setVisible(true);
        crearp.setVisible(false);
        pactualizar.setVisible(true);
        peliminar.setVisible(false);
    }//GEN-LAST:event_actualizarpActionPerformed

    private void eliminarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarpActionPerformed
        plibro.setVisible(false);
        librop.setVisible(false);
        usuariop.setVisible(false);
        pusuario.setVisible(false);
        fechap.setVisible(false);
        pfecha.setVisible(false);
        dfecha.setVisible(false);
        fechad.setVisible(false);
        idp.setVisible(true);
        idpnuevo.setVisible(true);
        crearp.setVisible(false);
        pactualizar.setVisible(false);
        peliminar.setVisible(true);
    }//GEN-LAST:event_eliminarpActionPerformed

    private void mostrarcategorias() {
        DefaultTableModel model = (DefaultTableModel) categoriatable.getModel();
        model.setRowCount(0);

        ArrayList<Categoria> categorias = new ArrayList();
        CategoriaController categoria = new CategoriaController();
        List<Categoria> leerc = categoria.leerCategorias();
        categorias.addAll(leerc);

        Object columnas[] = new Object[2];
        for (Categoria c : categorias) {
            columnas[0] = c.getCategoria_id();
            columnas[1] = c.getNombre();

            model.addRow(columnas);
        }
    }

    private void mostrarusuarios() {
        DefaultTableModel model = (DefaultTableModel) usuariotable.getModel();
        model.setRowCount(0);

        ArrayList<Usuario> usuarios = new ArrayList();
        UsuarioController usuario = new UsuarioController();
        List<Usuario> leeru = usuario.leerUsuario();
        usuarios.addAll(leeru);

        Object columnas[] = new Object[4];
        for (Usuario u : usuarios) {
            columnas[0] = u.getId_usuario();
            columnas[1] = u.getNombre();
            columnas[2] = u.getEmail();
            columnas[3] = u.getTelefono();
            model.addRow(columnas);

        }
    }

    private void mostrarprestamos() {
        DefaultTableModel model = (DefaultTableModel) prestamotable.getModel();
        model.setRowCount(0);

        ArrayList<Prestamo> prestamos = new ArrayList();
        PrestamoController prestamo = new PrestamoController();
        List<Prestamo> leerp = prestamo.leerPrestamos();
        prestamos.addAll(leerp);

        Object columnas[] = new Object[5];
        for (Prestamo p : prestamos) {
            columnas[0] = p.getId_prestamo();
            columnas[1] = p.getId_libroprestamo();
            columnas[2] = p.getId_usuarioprestamo();
            columnas[3] = p.getFecha_prestamo();
            columnas[4] = p.getFecha_devolucion();
            model.addRow(columnas);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton actualizarc;
    private javax.swing.JButton actualizarp;
    private javax.swing.JButton actualizaru;
    private javax.swing.JButton actualizarusuario;
    private javax.swing.JTextField anol;
    private javax.swing.JTextField autorl;
    private javax.swing.JButton botonactualizar;
    private javax.swing.JButton botoneliminar;
    private javax.swing.JButton butoncrear;
    private javax.swing.JButton cactualizar;
    private javax.swing.JTable categoriatable;
    private javax.swing.JButton ccrear;
    private javax.swing.JButton celiminar;
    private javax.swing.JLabel cid;
    private javax.swing.JLabel cnombre;
    private javax.swing.JButton consultarp;
    private javax.swing.JButton consultaru;
    private javax.swing.JButton crearc;
    private javax.swing.JButton crearl;
    private javax.swing.JButton crearp;
    private javax.swing.JButton crearprestamo;
    private javax.swing.JButton crearusuario;
    private javax.swing.JTextField dfecha;
    private javax.swing.JTextField editoriall;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton eliminarc;
    private javax.swing.JButton eliminarp;
    private javax.swing.JButton eliminarusuario;
    private javax.swing.JButton elinminaru;
    private javax.swing.JLabel emailu;
    private javax.swing.JLabel fechad;
    private javax.swing.JLabel fechap;
    private javax.swing.JTextField idc;
    private javax.swing.JTextField idl;
    private javax.swing.JLabel idp;
    private javax.swing.JTextField idpnuevo;
    private javax.swing.JLabel idu;
    private javax.swing.JTextField isbnl;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel lano;
    private javax.swing.JLabel lautor;
    private javax.swing.JLabel leditorial;
    private javax.swing.JLabel librop;
    private javax.swing.JTable librotable;
    private javax.swing.JLabel lid;
    private javax.swing.JLabel lisbn;
    private javax.swing.JLabel ltitulo;
    private javax.swing.JButton mostarc;
    private javax.swing.JButton mostrar;
    private javax.swing.JTextField nombrec;
    private javax.swing.JTextField nombrel;
    private javax.swing.JLabel nombreu;
    private javax.swing.JButton pactualizar;
    private javax.swing.JButton peliminar;
    private javax.swing.JTextField pfecha;
    private javax.swing.JTextField plibro;
    private javax.swing.JTable prestamotable;
    private javax.swing.JTextField pusuario;
    private javax.swing.JButton registrar;
    private javax.swing.JLabel telefonou;
    private javax.swing.JTextField usuarioe;
    private javax.swing.JTextField usuarioid;
    private javax.swing.JTextField usuarion;
    private javax.swing.JLabel usuariop;
    private javax.swing.JTextField usuariot;
    private javax.swing.JTable usuariotable;
    // End of variables declaration//GEN-END:variables
}
